services:
  php2:
    image: php:8.3-fpm
    build: .
    container_name: php2
    volumes:
      - ./products-microservice:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      - SYMFONY_ENV=dev
    ports:
      - "9002:9000"
    depends_on:
      - mariadb2

  mariadb2:
    image: mariadb:latest
    container_name: mariadb2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3308:3306" # Le port local est maintenant 3308
    volumes:
      - db_data:/var/lib/mysql

  nginx2:
    image: nginx:latest
    container_name: nginx2
    ports:
      - "8082:80"
    volumes:
      - ./products-microservice:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2

  phpmyadmin2:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin2
    environment:
      PMA_HOST: mariadb2 # Nom du conteneur MariaDB
      PMA_PORT: 3306    # Port interne utilisé par phpMyAdmin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8083:80" # Accès à phpMyAdmin via le port 8083
    depends_on:
      - mariadb2

volumes:
  db_data:

networks:
  default:
    external:
      name: microservices-network
